### ISSUE TITLE
Please add a mention to Nova Code & Coffee

### ISSUE THREAD

**Issue by kalimar** [Code-and-Coffee-Uptown-Brigade/Code-and-Coffee-Uptown-Brigade.github.io#10]
Hi folks,
We're super psyched that you folks started Uptown Brigade. We also noticed you are using the code developed by [Casey Watts](https://github.com/caseywatts). Would you be willing to add a mention to us and Casey?

Thanks

**Comment by csethna** [comment]
Yeah for sure! We will be meeting this Thursday and will address then. Thanks for the inspiration! Will update issue when completed. Cheers.

**Comment by kalimar** [comment]
Woot - thanks. Also, if you like feel free to submit a PR with a link to your site to this repo https://github.com/tech-meetup-website/tech-meetup-website.

**Comment by caseywatts** [comment]
Awesome thanks!

I'd recommend:
- adding the site to tech-meetup-website list in the readme
- adding a "fork me on GitHub" ribbon or something like that to your site
- putting attribution in the readme of your site

This is the first site someone used our tools for I've heard of that wasn't me doing it lol this is exciting for me :)
I'll add these guidelines to our repos sometime soon too, thanks for inspiring this.

**Comment by csethna** [comment]
Thanks for the guidance. Happy to attribute to you folks in the readme. It's done, feel free to have a look [here](https://github.com/Code-and-Coffee-Uptown-Brigade/Code-and-Coffee-Uptown-Brigade.github.io/blob/master/README.md). Cheers!

**Comment by kalimar** [comment]
Hi Cyrus,
Thanks for being so quick! All the best,
Kalimar
